{
(** Incremental lexical analysis for MiniML, generated by [ocamllex].

    The generated automaton owns a mutable {!Lexing.lexbuf}; callers consume it
    sequentially with {!next_token}. Lexer actions themselves use no explicit
    references or mutable user-defined state. *)

open Token
open Error_monad

(** The lexer state consumed by [next_token]. *)
type t = Lexing.lexbuf

(** [from_string input] returns a lexer over an in-memory string, positioned at
    line 1, column 1. *)
let from_string input = Lexing.from_string input

(** [from_channel channel] returns a lexer which refills its internal buffer
    from [channel] on demand. The complete input is not loaded up front. *)
let from_channel channel = Lexing.from_channel channel

(** [from_stdin ()] returns a buffered lexer reading from standard input. *)
let from_stdin () = from_channel stdin

(** [from_function refill] creates a streaming lexer. [refill buffer length]
    writes at most [length] bytes into [buffer] and returns the number written;
    returning [0] marks end of input. *)
let from_function refill = Lexing.from_function refill

(** Backwards-compatible alias for {!from_string}. *)
let create = from_string

let point_at_start lexbuf =
  Location.of_lexing_position (Lexing.lexeme_start_p lexbuf)
;;

let located lexbuf token = { token; span = Location.of_lexbuf lexbuf }

let integer_token lexbuf text =
  match int_of_string_opt text with
  | Some value -> return (located lexbuf (INT value))
  | None -> error (point_at_start lexbuf) "integer literal is out of range"
;;

let operator_token lexbuf text =
  match operator_of_lexeme text with
  | Some token -> return (located lexbuf token)
  | None -> error (point_at_start lexbuf) (Printf.sprintf "unknown operator %S" text)
;;

let unexpected_character lexbuf character =
  error
    (point_at_start lexbuf)
    (Printf.sprintf "unexpected character %C" character)
;;
}

let digit = ['0'-'9']
let integer = digit+
let identifier_start = ['a'-'z' 'A'-'Z' '_']
let identifier_continue = ['a'-'z' 'A'-'Z' '0'-'9' '_' '\'']
let identifier = identifier_start identifier_continue*
let horizontal_whitespace = [' ' '\t' '\r']+
let operator_character =
  ['!' '$' '%' '&' '*' '+' '-' '.' '/' ':' '<' '=' '>' '?' '@' '^' '|' '~']
let operator = operator_character+

rule read = parse
  | horizontal_whitespace { read lexbuf }
  | '\n'                  { Lexing.new_line lexbuf; read lexbuf }
  | "(*"                  {
      let open Syntax in
      let comment_start = point_at_start lexbuf in
      let* () = comment comment_start 1 lexbuf in
      read lexbuf
    }
  | integer as text       { integer_token lexbuf text }
  | identifier as text    { return (located lexbuf (keyword_or_identifier text)) }
  | "->"                  { return (located lexbuf ARROW) }
  | operator as text      { operator_token lexbuf text }
  | '('                   { return (located lexbuf LPAREN) }
  | ')'                   { return (located lexbuf RPAREN) }
  | '['                   { return (located lexbuf LBRACKET) }
  | ']'                   { return (located lexbuf RBRACKET) }
  | ','                   { return (located lexbuf COMMA) }
  | ';'                   { return (located lexbuf SEMICOLON) }
  | eof                   { return (located lexbuf EOF) }
  | _ as character        { unexpected_character lexbuf character }

and comment comment_start depth = parse
  | "(*" { comment comment_start (depth + 1) lexbuf }
  | "*)" {
      if depth = 1
      then return ()
      else comment comment_start (depth - 1) lexbuf
    }
  | '\n' { Lexing.new_line lexbuf; comment comment_start depth lexbuf }
  | eof  { error comment_start "unterminated comment" }
  | _    { comment comment_start depth lexbuf }

{
(** [next_token lexer] consumes and returns one located token. Whitespace and
    nested comments are skipped. *)
let next_token = read

(** Consume [lexer] and return all located tokens, including the final [EOF]. *)
let tokenize_lexer lexer =
  let rec loop reversed lexer =
    let open Syntax in
    let* located = next_token lexer in
    match located.token with
    | EOF -> return (List.rev (located :: reversed))
    | _ -> loop (located :: reversed) lexer
  in
  loop [] lexer
;;

(** Consume a string and return all located tokens, including [EOF]. *)
let tokenize input = tokenize_lexer (from_string input)

(** Like {!tokenize_lexer}, but discard source ranges. *)
let tokens_of_lexer lexer =
  map (tokenize_lexer lexer) (List.map (fun located -> located.token))
;;

(** Like {!tokenize}, but discard source ranges. *)
let tokens input = tokens_of_lexer (from_string input)
}
