{
[@@@ocaml.text "/*"]

(** Copyright 2026, Mikhail and contributors *)

(** SPDX-License-Identifier: LGPL-3.0-or-later *)

[@@@ocaml.text "/*"]

(** Demand-driven lexical analysis for MiniML, generated by [ocamllex].

    A lexer keeps only a {!Lexing.lexbuf}. Calling {!next_token} advances it
    by one token. Channel and callback sources are refilled by [Lexing] only
    when the automaton needs more input. *)

open Token
open Error_monad

(** A buffered input together with its current lexical position. *)
type t = Lexing.lexbuf

(** Create a demand-driven lexer over an existing string. *)
let from_string input = Lexing.from_string input

(** Create a demand-driven buffered lexer over a channel. *)
let from_channel channel = Lexing.from_channel channel

(** Create a demand-driven buffered lexer over standard input. *)
let from_stdin () = from_channel stdin

(** Create a lexer using [refill] as its input callback. The callback is
    invoked only when more input is required. *)
let from_function refill = Lexing.from_function refill

let point_at_start lexbuf =
  Location.of_lexing_position (Lexing.lexeme_start_p lexbuf)
;;

let located lexbuf token = { token; span = Location.of_lexbuf lexbuf }

let integer_token lexbuf text =
  match int_of_string_opt text with
  | Some value -> return (located lexbuf (INT value))
  | None -> error (point_at_start lexbuf) "integer literal is out of range"
;;

let operator_token lexbuf text =
  match operator_of_lexeme text with
  | Some token -> return (located lexbuf token)
  | None -> error (point_at_start lexbuf) (Printf.sprintf "unknown operator %S" text)
;;

let unexpected_character lexbuf character =
  error
    (point_at_start lexbuf)
    (Printf.sprintf "unexpected character %C" character)
;;

let invalid_identifier lexbuf text =
  error
    (point_at_start lexbuf)
    (Printf.sprintf "invalid identifier %S: identifiers cannot start with a digit" text)
;;
}

let digit = ['0'-'9']
let integer = digit+
let identifier_start = ['a'-'z' 'A'-'Z' '_']
let identifier_continue = ['a'-'z' 'A'-'Z' '0'-'9' '_' '\'']
let identifier = identifier_start identifier_continue*
let invalid_identifier = integer identifier_start identifier_continue*
let horizontal_whitespace = [' ' '\t' '\r']+
let operator_character =
  ['!' '$' '%' '&' '*' '+' '-' '.' '/' ':' '<' '=' '>' '?' '@' '^' '|' '~']
let operator = operator_character+

rule read = parse
  | horizontal_whitespace { read lexbuf }
  | '\n'                  { Lexing.new_line lexbuf; read lexbuf }
  | "(*"                  {
      let open Syntax in
      let comment_start = point_at_start lexbuf in
      let* () = comment comment_start 1 lexbuf in
      read lexbuf
    }
  | invalid_identifier as text { invalid_identifier lexbuf text }
  | integer as text       { integer_token lexbuf text }
  | identifier as text    { return (located lexbuf (keyword_or_identifier text)) }
  | "->"                  { return (located lexbuf ARROW) }
  | operator as text      { operator_token lexbuf text }
  | '('                   { return (located lexbuf LPAREN) }
  | ')'                   { return (located lexbuf RPAREN) }
  | eof                   { return (located lexbuf EOF) }
  | _ as character        { unexpected_character lexbuf character }

and comment comment_start depth = parse
  | "(*" { comment comment_start (depth + 1) lexbuf }
  | "*)" {
      if depth = 1
      then return ()
      else comment comment_start (depth - 1) lexbuf
    }
  | '\n' { Lexing.new_line lexbuf; comment comment_start depth lexbuf }
  | eof  { error comment_start "unterminated comment" }
  | _    { comment comment_start depth lexbuf }

{
(** Consume and return exactly one located token. Whitespace and comments are
    skipped as part of the same request. Repeated calls after EOF return EOF. *)
let next_token = read
}
