(test
 (name pretty_printer_test)
 (package MMML)
 (modules pretty_printer_test)
 (libraries MMML.frontend))

(test
 (name lexer_test)
 (package MMML)
 (modules lexer_test)
 (libraries MMML.frontend qcheck))

(test
 (name lexer_qcheck)
 (package MMML)
 (modules lexer_qcheck)
 (libraries MMML.frontend qcheck))
