name: CI

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ci-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: "5.5.1"

      - name: Install dependencies
        run: |
          opam pin add zanuda https://github.com/Kakadu/zanuda.git --no-action
          opam install . --depext-only --with-test
          opam install . --deps-only --with-test
          opam install ocamlformat.0.29.0 zanuda

      - name: Check formatting
        run: opam exec -- dune build @fmt

      - name: Build
        run: opam exec -- dune build @all @check --profile=release

      - name: Test
        run: opam exec -- dune runtest --profile=release

      - name: Lint
        run: opam exec -- zanuda -dir .
